config/routes.rb
Rails.application.routes.draw do
  get "setpassword", to: "setpassword#index"
  post "setpassword", to: "setpassword#create"
  get "page", to: "page#index"
  get "login", to: "login#index"
  post "login", to: "login#create"
  root "login#index"
  get "registration", to: "registration#index"
  post "registration", to: "registration#create"
  delete "login", to: "login#destroy"
  get "page/update_calendar"

  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  validates :FirstName, presence: true
  validates :LastName, presence: true
  validates :DateOfBirth, presence: { message: "Please fill in your birth date correctly." }
  validates :Gender, presence: true, inclusion: { in: [ "Male", "Female" ] }
  validates :Email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :PhoneNumber, presence: true, format: { with: /\A\d{10}\z/ }
  validates :Subject, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  def manifest
    render json: File.read(Rails.root.join("public", "manifest.json")), content_type: "application/json"
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end

  def create
    email = params[:login][:Email]
    phone_number = params[:login][:PhoneNumber]
    password = params[:login][:PhoneNumber]

    @user = UserInfo.find_by(Email: email, password: password)
    if @user
      session[:user_email] = @user.Email
      redirect_to controller: :page, action: :index
    else
      @user_first = UserInfo.find_by(Email: email, PhoneNumber: phone_number)
      if @user_first
        if @user_first.password.blank?
          session[:user_email] = @user_first.Email
          redirect_to controller: :setpassword, action: :index
        else
          render turbo_stream: turbo_stream.update("error-messages", partial: "login/form_errors", locals: { errors: [ "Invalid user or password" ] })
        end
      else
        render turbo_stream: turbo_stream.update("error-messages", partial: "login/form_errors", locals: { errors: [ "Invalid user or password" ] })
      end
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: "Logged out successfully!"
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user

  def index
    @user = UserInfo.all
    @current_date = params[:date] ? Date.parse(params[:date]) : Date.today
    @users = UserInfo.where.not(password: [ nil, "" ]).to_a
    @birthdays = {}
    @users.each do |user|
      if user.DateOfBirth.present?
        date_key = user.DateOfBirth.strftime("%m-%d")
        @birthdays[date_key] ||= []
        @birthdays[date_key] << user
      end
    end
  end

  def update_calendar
    @current_date = Date.parse(params[:date])
    @users = UserInfo.where.not(password: [ nil, "" ]).to_a
    @birthdays = {}
    @users.each do |user|
      if user.DateOfBirth.present?
        date_key = user.DateOfBirth.strftime("%m-%d")
        @birthdays[date_key] ||= []
        @birthdays[date_key] << user
      end
    end

    respond_to do |format|
      format.turbo_stream
    end
  end

  def authenticate_user
    if session[:user_email].present?
      # puts "--------------------------------------------------------------"
      # puts "Session found: #{session[:user_email]}"
    else
      # puts "--------------------------------------------------------------"
      # puts "Session not found"
      redirect_to controller: :login, action: :index
    end
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def index
    @user_info = UserInfo.new
  end

  def create
    # puts "--------------------------------------------------------------"
    @user_info = UserInfo.new(user_info_params)

    if @user_info.save
      flash[:success] = "registration success"
      redirect_to action: :index
      # puts "--------------------------------------------------------------"
      # puts "User info saved"
    else
      flash.now[:error] = "registration failed"
      # puts "--------------------------------------------------------------"
      # puts "User info not saved"
      render turbo_stream: turbo_stream.update("error-messages", partial: "registration/form_errors", locals: { errors: @user_info.errors.full_messages })
    end
  end

  private
  def user_info_params
    params.require(:user_info).permit(:FirstName, :LastName, :DateOfBirth, :Gender, :Email, :PhoneNumber, :Subject)
  end
end

app/controllers/service_worker_controller.rb
class ServiceWorkerController < ApplicationController
  protect_from_forgery except: :service_worker
  def service_worker
  end
  def manifest
  end
end

app/controllers/setpassword_controller.rb
class SetpasswordController < ApplicationController
  before_action :authenticate_user

  def index
  end

  def create
    email = session[:user_email]
    password= params[:setpassword][:password]
    password_confirmation = params[:setpassword][:password_confirm]
    # puts "--------------------------------------------------------------"
    # puts "Email: #{email}"
    # puts "Password: #{password}"
    # puts "Password Confirmation: #{password_confirmation}"
    if password != password_confirmation
      # puts "--------------------------------------------------------------"
      # puts "Passwords do not match"
      render turbo_stream: turbo_stream.update("error-messages", partial: "setpassword/form_errors", locals: { errors: [ "Passwords do not match" ] })
    else
      @user = UserInfo.find_by(Email: email)
      @user.update(password: password)
      # puts "--------------------------------------------------------------"
      # puts "Password updated"
      redirect_to controller: :page, action: :index
    end
  end

  def authenticate_user
    if session[:user_email].present?
      # puts "--------------------------------------------------------------"
      # puts "Session found: #{session[:user_email]}"
    else
      # puts "--------------------------------------------------------------"
      # puts "Session not found"
      redirect_to controller: :login, action: :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/setpassword_helper.rb
module SetpasswordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= content_for(:title) || "netdy-birthday" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    
    <link rel="manifest" crossorigin="use-credentials" href="/manifest.json" />
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta name="theme-color" content="#000000">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/apple-touch-icon.png" type="image/png">
    <link rel="icon" href="/apple-touch-icon.png" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('calendar-solid.svg') %>
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<body>
  <div class="form-container" style="max-width: 400px">
    <h1>Login</h1>
    <turbo-frame id="error-messages">
    </turbo-frame>
    <%= form_with(url: login_path, method: :post, remote: true) do |form| %>

    
    <div class="form-group">
      <%= form.label :Email, "Email" %>
      <%= form.email_field :Email, name: 'login[Email]', required: true %>
    </div>

    <div class="form-group">
      <%= form.label :PhoneNumber, "Password" %>
      <%= form.password_field :PhoneNumber, name: 'login[PhoneNumber]', required: true  %>
    </div>
    <h6 style="margin:0; color:#626262;">* If you login first time, please enter your phone number. </h6>

    <div class="form-group full-width">
      <%= form.submit "Login" %>
    </div>
    <p style="color:#545454">If you don't have an account, <a href="/registration" style="color : red; "> register here. </a></p>

<% end %>
    
  </div>
  
</body>

app/views/page/_calendar.html.erb
<div id="calendar">
  <div class="calendar-header">
    <%= link_to "&lt;".html_safe, page_update_calendar_path(date: @current_date.prev_month), class: "turbo-stream-link", data: { turbo_stream: true } %>
      <h2 id="month-year"><%= @current_date.strftime("%B") %> <%= @current_date.year + 543 %></h2>
    <%= link_to "&gt;".html_safe, page_update_calendar_path(date: @current_date.next_month), class: "turbo-stream-link", data: { turbo_stream: true } %>
  </div>
  <table>
    <thead>
      <tr>
        <th>Sun</th>
        <th>Mon</th>
        <th>Tue</th>
        <th>Wed</th>
        <th>Thu</th>
        <th>Fri</th>
        <th>Sat</th>
      </tr>
    </thead>
    <tbody id="calendar-body">
      <% start_date = @current_date.beginning_of_month.beginning_of_week %>
      <% end_date = @current_date.end_of_month.end_of_week %>
      <% (start_date..end_date).to_a.in_groups_of(7, false).each do |week| %>
        <tr>
          <% week.each do |day| %>
            <td class="<%= 'current-month' if day.month == @current_date.month %>"
                data-date="<%= day.to_s %>">
              <div class="date"><%= day.day %></div>
              <% if @birthdays && @birthdays[day.strftime("%m-%d")].present? %>
                <div class="birthday-info">
                  🎂
                  <div class="birthday-names">
                    <% @birthdays[day.strftime("%m-%d")].each do |user| %>
                      <div class="name" title="<%= "#{user.FirstName} #{user.LastName}" %>">
                        <%= "#{user.FirstName} #{user.LastName}" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/page/index.html.erb
<body>
    <div class="container-page">
        <div class="canlendar-header">
            <h1>🎂 Odds Birthday Calendar 🎂</h1>
        <%= render 'calendar' %>
         </div>   
<h1 class="page-title">UserInfo Table</h1>
<div class="table-container">
<table class="user-info-table">
  <thead>
    <tr>
      <th class="table-header">First Name</th>
      <th class="table-header">Last Name</th>
      <th class="table-header">Gender</th>
      <th class="table-header">Birthday</th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user_info| %>
      <tr class="table-row">
        <td class="table-data"><%= user_info.FirstName %></td>
        <td class="table-data"><%= user_info.LastName %></td>
        <td class="table-data"><%= user_info.Gender %></td> 
        <td class="table-data"><%= user_info.DateOfBirth %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= button_to 'Logout', login_path, method: :delete, style:"",class: 'logout-button' %>

</div>
</body>

app/views/page/update_calendar.turbo_stream.erb
<%= turbo_stream.replace "calendar" do %>
  <%= render 'calendar' %>
<% end %>

app/views/setpassword/_form_errors.html.erb
<div class="alert alert-danger">
  <%= errors.join(", ") %>
</div>

app/views/setpassword/index.html.erb
<body>
  <div class="form-container" style="max-width: 400px">
    <p style="color:#545454"><a href="/login" style="color : red; ">  &#60; Back  </a></p>
    <h1>Set Password</h1>
    
    <%= form_with(url: setpassword_path, method: :post, remote: true) do |form| %>
    
    <div class="form-group">
      <%= form.label :Password, "Set Password" %>
      <%= form.password_field  :Email, name: 'setpassword[password]', required: true , minlength:1, maxlength: 30%>
    </div>

    <div class="form-group">
      <%= form.label :PhoneNumber, "Comfirm Password" %>
      <%= form.password_field :PhoneNumber, name: 'setpassword[password_confirm]', required: true ,minlength: 1 , maxlength: 30  %>
    </div>

    <div class="form-group full-width">
      <%= form.submit "Submit" %>
    </div>

<% end %>
 <turbo-frame id="error-messages">
    </turbo-frame>

  </div>
</body>